POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNha29zaGFraWIiLCJpZCI6IjYwYWU3MTg0NjQzZmQwMDgzODUyNzdlNSIsImlhdCI6MTYyMjA1Mjc3NiwiZXhwIjoxNjIyMDU2Mzc2fQ.3FjWoIOBgflSdlgM8PYfhdi94DmuN2EP-MyLrMW2aWU 

{
    "title": "Ayyy",
    "author": "Mikyle Mirza",
    "url": "https://github.com/mikylemirza",
    "likes": 11
}

###
DELETE http://localhost:3003/api/blogs/60afe24a8fcfad0b77e56993
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNha29zaGFraWIiLCJpZCI6IjYwYWU3MTg0NjQzZmQwMDgzODUyNzdlNSIsImlhdCI6MTYyMjE0MjI3NSwiZXhwIjoxNjIyMTQ1ODc1fQ.uogr9I_Oss5owpT1-5HKup2-7DtV-sJm7To_rlDmFCk

###
DELETE http://localhost:3003/api/blogs/60afef981a14bc13d8d838ea
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNha29zaGFraWIiLCJpZCI6IjYwYWU3MTg0NjQzZmQwMDgzODUyNzdlNSIsImlhdCI6MTYyMjE0MjI3NSwiZXhwIjoxNjIyMTQ1ODc1fQ.uogr9I_Oss5owpT1-5HKup2-7DtV-sJm7To_rlDmFCk

